# theme = "cyan_light"
# theme = "everforest_dark"
# theme = "acme"
theme = "autumn"

[editor]
auto-format = true
line-number = "relative"
mouse = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_up"
# C-a = ":reload-all"
"space" = { e = ":w", "." = "file_picker_in_current_buffer_directory"} 

"D" = "extend_to_line_end"

S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]


C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
